name: 'Packages Build'
on:
  push:
    branches:
      - 'v4.3address32'

jobs:
  build:
    strategy:
      matrix:
        node: [18]
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install --ignore-scripts
      - run: yarn build
      - run: cd .. && tar -cjf web3js.tar.bz2 web3.js
      - uses: actions/upload-artifact@v3
        with:
          name: web3js
          path: /home/runner/work/web3.js/web3js.tar.bz2
